# Generated by Django 3.0.4 on 2020-03-24 18:36

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0002_auto_20200324_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professorreview',
            old_name='Name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='professorreview',
            name='course',
        ),
        migrations.AddField(
            model_name='professorreview',
            name='courses',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='professorreview',
            name='difficulty',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('content', models.TextField()),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('rating', models.IntegerField()),
                ('difficulty', models.CharField(blank=True, max_length=20)),
                ('professor', models.CharField(max_length=20)),
                ('requirements', models.CharField(blank=True, max_length=20)),
                ('recommended_for', models.TextField(blank=True)),
                ('author', models.ForeignKey(on_delete=models.SET('[Deleted]'), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
