# Generated by Django 3.0.4 on 2020-03-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20200325_0006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursereview',
            old_name='content',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='coursereview',
            old_name='professor',
            new_name='taught_by',
        ),
        migrations.RenameField(
            model_name='professorreview',
            old_name='content',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='professorreview',
            old_name='courses',
            new_name='courses_taught',
        ),
        migrations.AlterField(
            model_name='coursereview',
            name='difficulty',
            field=models.CharField(max_length=20),
        ),
    ]
