# Generated by Django 3.0.4 on 2020-03-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_course_professor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='difficulty',
        ),
        migrations.AddField(
            model_name='course',
            name='total',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='coursereview',
            name='changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='professorreview',
            name='changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='professor',
            name='total',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
